In [1]:
import pandas as pd
df=pd.read_csv("/content/Covid Vaccine Statewise.csv")
df.head()

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,India,48276.0,3455.0,2957.0,48276.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23757.0,24517.0,2.0,48276.0
1,17/01/2021,India,58604.0,8532.0,4954.0,58604.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,27348.0,31252.0,4.0,58604.0
2,18/01/2021,India,99449.0,13611.0,6583.0,99449.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,41361.0,58083.0,5.0,99449.0
3,19/01/2021,India,195525.0,17855.0,7951.0,195525.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,81901.0,113613.0,11.0,195525.0
4,20/01/2021,India,251280.0,25472.0,10504.0,251280.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,98111.0,153145.0,24.0,251280.0

#1.Describe the Dataset

In [8]:
# a. Describe the dataset
print("Dataset Description:")
print("\nShape of dataset:", df.shape)
print("_____________________________________________________________________")
print("\nColumns in dataset:")
print(df.columns)
print("_____________________________________________________________________")
print("\nFirst few rows:")
print(df.head())
print("_____________________________________________________________________")
print("\nDataset Info:")
print(df.info())
print("_____________________________________________________________________")
print("\nDataset Statistics:")
print(df.describe())

Dataset Description:

Shape of dataset: (7845, 24)
_____________________________________________________________________

Columns in dataset:
Index(['Updated On', 'State', 'Total Doses Administered', 'Sessions',
       ' Sites ', 'First Dose Administered', 'Second Dose Administered',
       'Male (Doses Administered)', 'Female (Doses Administered)',
       'Transgender (Doses Administered)', ' Covaxin (Doses Administered)',
       'CoviShield (Doses Administered)', 'Sputnik V (Doses Administered)',
       'AEFI', '18-44 Years (Doses Administered)',
       '45-60 Years (Doses Administered)', '60+ Years (Doses Administered)',
       '18-44 Years(Individuals Vaccinated)',
       '45-60 Years(Individuals Vaccinated)',
       '60+ Years(Individuals Vaccinated)', 'Male(Individuals Vaccinated)',
       'Female(Individuals Vaccinated)', 'Transgender(Individuals Vaccinated)',
       'Total Individuals Vaccinated'],
      dtype='object')
_____________________________________________________________________

First few rows:
   Updated On  State  Total Doses Administered  Sessions   Sites   \
0  16/01/2021  India                   48276.0    3455.0   2957.0
1  17/01/2021  India                   58604.0    8532.0   4954.0
2  18/01/2021  India                   99449.0   13611.0   6583.0
3  19/01/2021  India                  195525.0   17855.0   7951.0
4  20/01/2021  India                  251280.0   25472.0  10504.0

   First Dose Administered  Second Dose Administered  \
0                  48276.0                       0.0
1                  58604.0                       0.0
2                  99449.0                       0.0
3                 195525.0                       0.0
4                 251280.0                       0.0

   Male (Doses Administered)  Female (Doses Administered)  \
0                        NaN                          NaN
1                        NaN                          NaN
2                        NaN                          NaN
3                        NaN                          NaN
4                        NaN                          NaN

   Transgender (Doses Administered)  ...  18-44 Years (Doses Administered)  \
0                               NaN  ...                               NaN
1                               NaN  ...                               NaN
2                               NaN  ...                               NaN
3                               NaN  ...                               NaN
4                               NaN  ...                               NaN

   45-60 Years (Doses Administered)  60+ Years (Doses Administered)  \
0                               NaN                             NaN
1                               NaN                             NaN
2                               NaN                             NaN
3                               NaN                             NaN
4                               NaN                             NaN

   18-44 Years(Individuals Vaccinated)  45-60 Years(Individuals Vaccinated)  \
0                                  NaN                                  NaN
1                                  NaN                                  NaN
2                                  NaN                                  NaN
3                                  NaN                                  NaN
4                                  NaN                                  NaN

   60+ Years(Individuals Vaccinated)  Male(Individuals Vaccinated)  \
0                                NaN                       23757.0
1                                NaN                       27348.0
2                                NaN                       41361.0
3                                NaN                       81901.0
4                                NaN                       98111.0

   Female(Individuals Vaccinated)  Transgender(Individuals Vaccinated)  \
0                         24517.0                                  2.0
1                         31252.0                                  4.0
2                         58083.0                                  5.0
3                        113613.0                                 11.0
4                        153145.0                                 24.0

   Total Individuals Vaccinated
0                       48276.0
1                       58604.0
2                       99449.0
3                      195525.0
4                      251280.0

[5 rows x 24 columns]
_____________________________________________________________________

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7845 entries, 0 to 7844
Data columns (total 24 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Updated On                           7845 non-null   object
 1   State                                7845 non-null   object
 2   Total Doses Administered             7621 non-null   float64
 3   Sessions                             7621 non-null   float64
 4    Sites                               7621 non-null   float64
 5   First Dose Administered              7621 non-null   float64
 6   Second Dose Administered             7621 non-null   float64
 7   Male (Doses Administered)            7461 non-null   float64
 8   Female (Doses Administered)          7461 non-null   float64
 9   Transgender (Doses Administered)     7461 non-null   float64
 10   Covaxin (Doses Administered)        7621 non-null   float64
 11  CoviShield (Doses Administered)      7621 non-null   float64
 12  Sputnik V (Doses Administered)       2995 non-null   float64
 13  AEFI                                 5438 non-null   float64
 14  18-44 Years (Doses Administered)     1702 non-null   float64
 15  45-60 Years (Doses Administered)     1702 non-null   float64
 16  60+ Years (Doses Administered)       1702 non-null   float64
 17  18-44 Years(Individuals Vaccinated)  3733 non-null   float64
 18  45-60 Years(Individuals Vaccinated)  3734 non-null   float64
 19  60+ Years(Individuals Vaccinated)    3734 non-null   float64
 20  Male(Individuals Vaccinated)         160 non-null    float64
 21  Female(Individuals Vaccinated)       160 non-null    float64
 22  Transgender(Individuals Vaccinated)  160 non-null    float64
 23  Total Individuals Vaccinated         5919 non-null   float64
dtypes: float64(22), object(2)
memory usage: 1.4+ MB
None
_____________________________________________________________________

Dataset Statistics:
       Total Doses Administered      Sessions        Sites   \
count              7.621000e+03  7.621000e+03   7621.000000
mean               9.188171e+06  4.792358e+05   2282.872064
std                3.746180e+07  1.911511e+06   7275.973730
min                7.000000e+00  0.000000e+00      0.000000
25%                1.356570e+05  6.004000e+03     69.000000
50%                8.182020e+05  4.547000e+04    597.000000
75%                6.625243e+06  3.428690e+05   1708.000000
max                5.132284e+08  3.501031e+07  73933.000000

       First Dose Administered  Second Dose Administered  \
count             7.621000e+03              7.621000e+03
mean              7.414415e+06              1.773755e+06
std               2.995209e+07              7.570382e+06
min               7.000000e+00              0.000000e+00
25%               1.166320e+05              1.283100e+04
50%               6.614590e+05              1.388180e+05
75%               5.387805e+06              1.166434e+06
max               4.001504e+08              1.130780e+08

       Male (Doses Administered)  Female (Doses Administered)  \
count               7.461000e+03                 7.461000e+03
mean                3.620156e+06                 3.168416e+06
std                 1.737938e+07                 1.515310e+07
min                 0.000000e+00                 2.000000e+00
25%                 5.655500e+04                 5.210700e+04
50%                 3.897850e+05                 3.342380e+05
75%                 2.735777e+06                 2.561513e+06
max                 2.701636e+08                 2.395186e+08

       Transgender (Doses Administered)   Covaxin (Doses Administered)  \
count                       7461.000000                   7.621000e+03
mean                        1162.978019                   1.044669e+06
std                         5931.353995                   4.452259e+06
min                            0.000000                   0.000000e+00
25%                            8.000000                   0.000000e+00
50%                          113.000000                   1.185100e+04
75%                          800.000000                   7.579300e+05
max                        98275.000000                   6.236742e+07

       CoviShield (Doses Administered)  ...  18-44 Years (Doses Administered)  \
count                     7.621000e+03  ...                      1.702000e+03
mean                      8.126553e+06  ...                      8.773958e+06
std                       3.298414e+07  ...                      2.660829e+07
min                       7.000000e+00  ...                      2.662400e+04
25%                       1.331340e+05  ...                      4.344842e+05
50%                       7.567360e+05  ...                      3.095970e+06
75%                       6.007817e+06  ...                      7.366241e+06
max                       4.468251e+08  ...                      2.243304e+08

       45-60 Years (Doses Administered)  60+ Years (Doses Administered)  \
count                      1.702000e+03                    1.702000e+03
mean                       7.442161e+06                    5.641605e+06
std                        2.225999e+07                    1.681650e+07
min                        1.681500e+04                    9.994000e+03
25%                        2.326275e+05                    1.285605e+05
50%                        2.695938e+06                    1.805696e+06
75%                        6.969726e+06                    5.294763e+06
max                        1.667575e+08                    1.186927e+08

       18-44 Years(Individuals Vaccinated)  \
count                         3.733000e+03
mean                          1.395895e+06
std                           5.501454e+06
min                           1.059000e+03
25%                           5.655400e+04
50%                           2.947270e+05
75%                           9.105160e+05
max                           9.224315e+07

       45-60 Years(Individuals Vaccinated)  60+ Years(Individuals Vaccinated)  \
count                         3.734000e+03                       3.734000e+03
mean                          2.916515e+06                       2.627444e+06
std                           9.567607e+06                       8.192225e+06
min                           1.136000e+03                       5.580000e+02
25%                           9.248225e+04                       5.615975e+04
50%                           8.330395e+05                       7.887425e+05
75%                           2.499280e+06                       2.337874e+06
max                           9.096888e+07                       6.731098e+07

       Male(Individuals Vaccinated)  Female(Individuals Vaccinated)  \
count                  1.600000e+02                    1.600000e+02
mean                   4.461687e+07                    3.951018e+07
std                    3.950749e+07                    3.417684e+07
min                    2.375700e+04                    2.451700e+04
25%                    5.739350e+06                    5.023407e+06
50%                    3.716590e+07                    3.365402e+07
75%                    7.441663e+07                    6.685368e+07
max                    1.349420e+08                    1.156684e+08

       Transgender(Individuals Vaccinated)  Total Individuals Vaccinated
count                           160.000000                  5.919000e+03
mean                          12370.543750                  4.547842e+06
std                           12485.026753                  1.834182e+07
min                               2.000000                  7.000000e+00
25%                            1278.750000                  7.427550e+04
50%                            8007.500000                  4.022880e+05
75%                           19851.000000                  3.501562e+06
max                           46462.000000                  2.506569e+08

[8 rows x 22 columns]

#2.Number of persons state wise vaccinated for first dose in India

In [25]:
# First Dose Analysis - Step by Step
# 1. Remove India from states (keep only individual states)
states_data = df[df['State'] != 'India']

# 2. Group by state and get first dose data
first_dose = states_data.groupby('State')['First Dose Administered'].max()
print("\nFirst Dose Vaccination by State :")
print(first_dose)

First Dose Vaccination by State :
State
Andaman and Nicobar Islands                   216046.0
Andhra Pradesh                              17628583.0
Arunachal Pradesh                             692475.0
Assam                                       10495293.0
Bihar                                       23350171.0
Chandigarh                                    700285.0
Chhattisgarh                                 9181482.0
Dadra and Nagar Haveli and Daman and Diu      584370.0
Delhi                                        7835546.0
Goa                                          1094392.0
Gujarat                                     28101222.0
Haryana                                     10086831.0
Himachal Pradesh                             4249849.0
Jammu and Kashmir                            5318516.0
Jharkhand                                    8382280.0
Karnataka                                   25847691.0
Kerala                                      15670747.0
Ladakh                                        188699.0
Lakshadweep                                    51156.0
Madhya Pradesh                              29723036.0
Maharashtra                                 35040812.0
Manipur                                      1159424.0
Meghalaya                                     938572.0
Mizoram                                       654946.0
Nagaland                                      632120.0
Odisha                                      13954592.0
Puducherry                                    601591.0
Punjab                                       8005636.0
Rajasthan                                   27008606.0
Sikkim                                        497851.0
Tamil Nadu                                  20836674.0
Telangana                                   11649268.0
Tripura                                      2411195.0
Uttar Pradesh                               45932488.0
Uttarakhand                                  5070544.0
West Bengal                                 23257417.0
Name: First Dose Administered, dtype: float64

#3. Number of persons state wise vaccinated for second dose in India

In [23]:
# Second Dose Analysis - Step by Step
# 1. Remove India from states (keep only individual states)
states_data = df[df['State'] != 'India']
# 2. Group by state and get first dose data
second_dose = states_data.groupby('State')['Second Dose Administered'].max()
print("\nSecond Dose Vaccination by State :")
print(second_dose)

Second Dose Vaccination by State :
State
Andaman and Nicobar Islands                    94597.0
Andhra Pradesh                               6214312.0
Arunachal Pradesh                             186619.0
Assam                                        2208577.0
Bihar                                        4484768.0
Chandigarh                                    223534.0
Chhattisgarh                                 2587695.0
Dadra and Nagar Haveli and Daman and Diu       80851.0
Delhi                                        3000536.0
Goa                                           302519.0
Gujarat                                      9051153.0
Haryana                                      2923550.0
Himachal Pradesh                             1382592.0
Jammu and Kashmir                            1489826.0
Jharkhand                                    1996014.0
Karnataka                                    7432852.0
Kerala                                       6426984.0
Ladakh                                         70337.0
Lakshadweep                                    17139.0
Madhya Pradesh                               5733640.0
Maharashtra                                 12112554.0
Manipur                                       246694.0
Meghalaya                                     231982.0
Mizoram                                       206773.0
Nagaland                                      159388.0
Odisha                                       4200094.0
Puducherry                                    151771.0
Punjab                                       2285629.0
Rajasthan                                    8375056.0
Sikkim                                        151538.0
Tamil Nadu                                   4686034.0
Telangana                                    3965624.0
Tripura                                       804099.0
Uttar Pradesh                                8515236.0
Uttarakhand                                  1596572.0
West Bengal                                  9132961.0
Name: Second Dose Administered, dtype: float64

#Why Use max() while grouping the data?
Data Context:

It appears that the dataset may contain multiple entries for each state, possibly representing data from different dates or reporting periods.
max() ensures that you capture the most updated (highest) value of "First Dose Administered" for each state.